let all_product = [
  {
    id: 1,
    name: "Peplum Hem Blouse with Flared Sleeves and Striped Collar",
    category: "WOMEN",
    image: "product_1.png",
    new_price: 50.0,
    old_price: 80.5,
  },
  {
    id: 2,
    name: "Peplum Hem Blouse with Flared Sleeves and Striped Collar",
    category: "WOMEN",
    image: "product_2.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 3,
    name: "Peplum Hem Blouse with Flared Sleeves and Striped Collar",
    category: "WOMEN",
    image: "product_3.png",
    new_price: 60.0,
    old_price: 100.5,
  },
  {
    id: 4,
    name: "Peplum Hem Blouse with Flared Sleeves and Striped Collar",
    category: "WOMEN",
    image: "product_4.png",
    new_price: 100.0,
    old_price: 150.0,
  },

  {
    id: 5,
    name: "Chemisier à ourlet peplum avec manches évasées à rayures et col",
    category: "WOMEN",
    image: "product_5.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 6,
    name: "Chemisier à ourlet peplum avec manches évasées à rayures et col",
    category: "WOMEN",
    image: "product_6.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 7,
    name: "Chemisier à ourlet peplum avec manches évasées à rayures et col",
    category: "WOMEN",
    image: "product_7.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 8,
    name: "Chemisier à ourlet peplum avec manches évasées à rayures et col",
    category: "WOMEN",
    image: "product_8.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 9,
    name: "Chemisier à ourlet peplum avec manches évasées à rayures et col",
    category: "WOMEN",
    image: "product_9.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 10,
    name: "Chemisier à ourlet peplum avec manches évasées à rayures et col",
    category: "WOMEN",
    image: "product_10.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 11,
    name: "Chemisier à ourlet peplum avec manches évasées à rayures et col",
    category: "WOMEN",
    image: "product_11.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 12,
    name: "Chemisier à ourlet peplum avec manches évasées à rayures et col",
    category: "WOMEN",
    image: "product_12.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 13,
    name: "Blouson de bombardier slim zippé vert pour homme",
    category: "MEN",
    image: "product_13.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 14,
    name: "Blouson de bombardier slim zippé vert pour homme",
    category: "MEN",
    image: "product_14.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 15,
    name: "Blouson de bombardier slim zippé vert pour homme",
    category: "MEN",
    image: "product_15.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 16,
    name: "Blouson de bombardier slim zippé vert pour homme",
    category: "MEN",
    image: "product_16.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 17,
    name: "Blouson de bombardier slim zippé vert pour homme",
    category: "MEN",
    image: "product_17.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 18,
    name: "Blouson de bombardier slim zippé vert pour homme",
    category: "MEN",
    image: "product_18.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 19,
    name: "Blouson de bombardier slim zippé vert pour homme",
    category: "MEN",
    image: "product_19.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 20,
    name: "Blouson de bombardier slim zippé vert pour homme",
    category: "MEN",
    image: "product_20.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 21,
    name: "Blouson de bombardier slim zippé vert pour homme",
    category: "MEN",
    image: "product_21.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 22,
    name: "Blouson de bombardier slim zippé vert pour homme",
    category: "MEN",
    image: "product_22.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 23,
    name: "Blouson de bombardier slim zippé vert pour homme",
    category: "MEN",
    image: "product_23.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 24,
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "MEN",
    image: "product_24.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 25,
    name: "Sweat à capuche orange à blocs de couleur pour garçons",
    category: "KID",
    image: "product_25.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 26,
    name: "Sweat à capuche orange à blocs de couleur pour garçons",
    category: "KID",
    image: "product_26.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 27,
    name: "Sweat à capuche orange à blocs de couleur pour garçons",
    category: "KID",
    image: "product_27.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 28,
    name: "Sweat à capuche orange à blocs de couleur pour garçons",
    category: "KID",
    image: "product_28.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 29,
    name: "Sweat à capuche orange à blocs de couleur pour garçons",
    category: "KID",
    image: "product_29.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 30,
    name: "Sweat à capuche orange à blocs de couleur pour garçons",
    category: "KID",
    image: "product_30.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 31,
    name: "Sweat à capuche orange à blocs de couleur pour garçons",
    category: "KID",
    image: "product_31.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 32,
    name: "Sweat à capuche orange à blocs de couleur pour garçons",
    category: "KID",
    image: "product_32.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 33,
    name: "Sweat à capuche orange à blocs de couleur pour garçons",
    category: "KID",
    image: "product_33.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 34,
    name: "Sweat à capuche orange à blocs de couleur pour garçons",
    category: "KID",
    image: "product_34.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 35,
    name: "Sweat à capuche orange à blocs de couleur pour garçons",
    category: "KID",
    image: "product_35.png",
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 36,
    name: "Sweat à capuche orange à blocs de couleur pour garçons",
    category: "KID",
    image: "product_36.png",
    new_price: 85.0,
    old_price: 120.5,
  },
];

export default all_product;
